from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


"""Update car listing models with enhanced fields

Revision ID: cd2586440722
Revises: 21bf6e2c4c5f
Create Date: 2025-06-04 13:07:21.452420

"""
# revision identifiers, used by Alembic.
revision = 'cd2586440722'
down_revision = '21bf6e2c4c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_listing_history', sa.Column('price_change', sa.Float(), nullable=True))
    op.add_column('car_listing_history', sa.Column('days_on_market', sa.Integer(), nullable=True))
    op.drop_constraint('car_listing_history_listing_id_fkey', 'car_listing_history', type_='foreignkey')
    op.create_foreign_key(None, 'car_listing_history', 'car_listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.add_column('car_listings', sa.Column('engine_cc', sa.String(length=20), nullable=True))
    op.add_column('car_listings', sa.Column('engine_type', sa.String(length=50), nullable=True))
    op.add_column('car_listings', sa.Column('condition', sa.String(length=50), nullable=True))
    op.add_column('car_listings', sa.Column('ownership', sa.String(length=50), nullable=True))
    op.add_column('car_listings', sa.Column('origin', sa.String(length=50), nullable=True))
    op.add_column('car_listings', sa.Column('test_date', sa.String(length=20), nullable=True))
    op.add_column('car_listings', sa.Column('hand', sa.String(length=10), nullable=True))
    op.add_column('car_listings', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('car_listings', sa.Column('url', sa.String(length=500), nullable=True))
    op.add_column('car_listings', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('car_listings', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('car_listings', sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('car_listings', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('car_listings', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('car_listings', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('car_listings', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('car_listings', 'image_url')
    op.drop_column('car_listings', 'last_scraped_at')
    op.drop_column('car_listings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_listings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('car_listings', sa.Column('last_scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('car_listings', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('car_listings', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car_listings', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car_listings', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car_listings', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('car_listings', 'scraped_at')
    op.drop_column('car_listings', 'images')
    op.drop_column('car_listings', 'source')
    op.drop_column('car_listings', 'url')
    op.drop_column('car_listings', 'location')
    op.drop_column('car_listings', 'hand')
    op.drop_column('car_listings', 'test_date')
    op.drop_column('car_listings', 'origin')
    op.drop_column('car_listings', 'ownership')
    op.drop_column('car_listings', 'condition')
    op.drop_column('car_listings', 'engine_type')
    op.drop_column('car_listings', 'engine_cc')
    op.drop_constraint(None, 'car_listing_history', type_='foreignkey')
    op.create_foreign_key('car_listing_history_listing_id_fkey', 'car_listing_history', 'car_listings', ['listing_id'], ['id'])
    op.drop_column('car_listing_history', 'days_on_market')
    op.drop_column('car_listing_history', 'price_change')
    # ### end Alembic commands ###
